
syntax = "proto3";

option go_package = "generated/pb/table";

option java_package = "com.game.table";


enum bag_error {
  kBag_errorOK = 0;

  kBagDeleteItemFindGuid = 6000;

  kBagDeleteItemAlreadyHasGuid = 6001;

  kBagAddItemHasNotBaseComponent = 6002;

  kBagAddItemInvalidGuid = 6003;

  kBagAddItemInvalidParam = 6004;

  kBagAddItemBagFull = 6005;

  kBagItemNotStacked = 6006;

  kBagInsufficientItems = 6007;

  kBagDelItemPos = 6008;

  kBagDelItemConfig = 6009;

  kBagDelItemGuid = 6010;

  kBagDelItemFindItem = 6011;

  kBagDelItemSize = 6012;

  kBagItemDeletionSizeMismatch = 6013;

  kBagInsufficientBagSpace = 6014;

};